# Generated by Django 6.1 on 2026-08-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
